swagger: '2.0'
info:
  version: 1.0.0
  title: Fastball Aerohockey API

schemes:
 - https
 - http

basePath: /api

consumes:
- application/json
produces:
- application/json

paths:
  /signup:
    post:
      summary: Регистрация нового пользователя
      description: |
        Регистрация нового пользователя. В случае успеха пользователь сразу авторизуется
      consumes: []
      parameters:
      - in: body
        name: Параметры
        required: true        
        description:
          \{ 
            "login":"...",
            "password":"...",
            "email":"..." 
          \}

        schema: 
          $ref: '#/definitions/User'
      responses:
        200:
          description: Пользователь зарегистрирован
          schema:
            $ref: '#/definitions/UserShort'
        400:
          description: Не все поля заполнены
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: В текущей сессии уже есть авторизованный пользователь
          schema:
            $ref: '#/definitions/ErrorResponse'
        409:
          description: Пользователь с таким логином уже существует
          schema:
            $ref: '#/definitions/ErrorResponse'
          
  /login:
    post:
      summary: Позволяет авторизоваться пользователю
      description: |
        Позволяет авторизоваться пользователю
      consumes: []
      parameters:
      - in: body
        name: Параметры
        required: true        
        description:
          \{ 
            "login":"...",
            "password":"...",
          \}

        schema: 
          $ref: '#/definitions/UserWithPassword'
      responses:
        200:
          description: Пользователь успешно авторизован
          schema:
            $ref: '#/definitions/UserShort'
        400:
          description: Не все поля заполнены
          schema:
            $ref: '#/definitions/ErrorResponse'
        401:
          description: Не верный логин/пароль
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: В текущей сессии уже есть авторизованный пользователь
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/ErrorResponse'
  
  /user:
    get:
      summary: Показать данные о текущем пользователе
      description: |
        Возвращает данные пользователя, если он авторизован
      consumes: []

      responses:
        200:
          description: Данные текущего пользователя
          schema:
            $ref: '#/definitions/UserShort'
        403:
          description: В сессии нет авторизованного пользователя
          schema:
            $ref: '#/definitions/ErrorResponse'
            
            
  /change-password:
    post:
      summary: Позволяет сменить пароль пользователю
      description: |
        Позволяет сменить пароль пользователю, только если пользователь авторизован
      consumes: []
      parameters:
      - in: body
        name: Параметры
        required: true        
        description:
          \{ 
            "old-password":"...",
            "password":"...",
          \}

        schema: 
          $ref: '#/definitions/ChangePassword'
      responses:
        200:
          description: Пароль успешно изменен
          schema:
            $ref: '#/definitions/UserShort'
        400:
          description: Не все поля заполнены
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: Старый пароль указан неверно/Пользователь не авторизован
          schema:
            $ref: '#/definitions/ErrorResponse'
            
            
  /change-user-data:
    post:
      summary: Позволяет сменить пользователю логин/email
      description: |
        Позволяет сменить пользователю логин/email, только если пользователь авторизован
      consumes: []
      parameters:
      - in: body
        name: Параметры
        required: true        
        description:
          \{ 
            "login":"...",
            "email":"...",
          \}

        schema: 
          $ref: '#/definitions/UserShort'
      responses:
        200:
          description: Данные успешно изменены
          schema:
            $ref: '#/definitions/UserShort'
        403:
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/ErrorResponse'
            
  /logout:
    post:
      summary: Позволяет разлогиниться пользователю
      consumes: []
      responses:
        200:
          description: Пользователь разлогинен
        403:
          description: Нет авторизованного пользователя в данной сессии
          schema:
            $ref: '#/definitions/ErrorResponse'


definitions:
  User:
    type: object
    description: |
        Пользователь
    properties:
      #id:
       # type: integer
       # format: long
        #readOnly: true
      login:
        type: string
      email:
        type: string
      password:
        type: string
        
  UserShort:
    type: object
    description: |
        Форма ответа на запрос
    properties:
      login:
        type: string
      email:
        type: string
        
  UserWithPassword:
    type: object
    description: |
        Форма для логина
    properties:
      login:
        type: string
      password:
        type: string
        
  ChangePassword:
    type: object
    description: |
        Форма для смена пароля  
    properties:
      old-password:
        type: string
      password:
        type: string
        
  ErrorResponse:
    type: object
    description: |
        Передает текст ошибки
    properties:
      error:
        type: string
